### ISSUE TITLE
Complete Vivace Tutorial

### ISSUE THREAD

**Issue by sethlivingston** [liballeg/allegro_wiki#1]
This actually isn't so much an issue to complete the tutorial as it is a **thank you** for what's there so far. Looking forward to the remaining chapters; it's very helpful!

**Comment by snoopdouglas** [comment]
People are reading it!? Brilliant. This makes me very happy. :p

Hoping to have some more time tomorrow to add to (and hopefully finish) the 'input' section.

**Comment by Knapperr** [comment]
I am definitely reading it!

**Comment by snoopdouglas** [comment]
I've now finished the section on keys, but I realise we still need a section on the mouse and joystick. I've never written code for the latter (somehow) so might ask for someone more familiar to do that...

**Comment by snoopdouglas** [comment]
[Input section's done](https://github.com/liballeg/allegro_wiki/wiki/Allegro-Vivace%3A-Input) - other than joysticks, my excuse being that a new developer may not have one to hand.

**Comment by stickleprojects** [comment]
really great tutorial, just got to "sound" and burst into tears :( loved it up to that point tho

**Comment by snoopdouglas** [comment]
@stickleprojects Haha oh man. I'm sorry. I've just navigated to the sound page... they could've at least left it red :p

I'll get back on this soon. Probably.

**Comment by EdwinMartens** [comment]
Well at least people are still looking at this.
Shall I give a hand completing it ?

**Comment by snoopdouglas** [comment]
Yeah, please do! It'd be good to at least get an outline for introducing the reader to programming audio.

After we've fleshed out the audio article, I reckon the biggest challenge will be coming up with some gameplay mechanics which are simple enough to fit into the tutorial, yet can be used to provide the reader with a solid base to build upon.

Any thoughts on what game we should present? Pong is the first thing that pops into my head

**Comment by stickleprojects** [comment]
if its any help, im writing a version of Preppie (like frogger, but but atari 8bit) using this tutorial and the allegro libs that i'd be happy to canablise or share https://github.com/stickleprojects/allegro (now public)

**Comment by stickleprojects** [comment]
slightly offtopic - looking into the music stuff and trying to get ANY music written on linux is complete PITA (going to switch to windows) - any recommendation on "if youre playing background music, you should use this format" or are they always really long mp3s?  here's the game and tune i wil be replicating to create something with Allegro based on this tutorial... https://www.youtube.com/watch?v=ut32gM6SmoE

**Comment by snoopdouglas** [comment]
One of the few reasons I have Windows installed is for FL Studio, which I've used since forever, so the cost of migrating for me is too high.

**However...** [Bitwig](https://www.bitwig.com/en/home.html) exists. If I was starting fresh, I'd absolutely use that on Linux.

As for what format to use, I'd personally go with long (and/or looped) Opus files for music. Their compression vs. MP3 is superior, and the Allegro audio codec addon includes support for them. For sound effects, I use FLAC.

**Comment by stickleprojects** [comment]
@snoopdouglas thanks for the recommendation but my music skills don't justify the commercials (just yet) and definitely this "game" doesnt - i will bear it in mind tho for future and for any recommendations i get asked... all i want is Octomed for linux - is that too much to ask (sigh) :)

**Comment by snoopdouglas** [comment]
Ah well, in that case you might want to either:

* [Emulate an Amiga](https://fs-uae.net/)
* Fork out a modest amount of cash for [Renoise](https://www.renoise.com/shop)
* Run [OpenMPT](https://openmpt.org/download) with WINE

**Comment by allefant** [comment]
Try LMMS, I use it for all my (amateurish attempts of creating) music.

**Comment by EdwinMartens** [comment]
"Luckily, sound in Allegro 5 is markedly simpler than what this Paul bloke is on about. If you just want to load a sample and play it, your life will be easy. If you want to put the fear of God into your players by creating an all-encompassing orchestral soundscape by juggling lots of samples and music, your life will be a bit more complicated."

Roflmao 😂

Great !

When I have time, all start a section about structuring the code a bit coming week.
Since Allegro is basicly 'C' I'll keep to that.
Though C++ is a bit more suited to do this.

**Comment by snoopdouglas** [comment]
> structuring the code

There's no right way to do this, so I figured we'd show *one way* in the gameplay section. By all means go ahead - let's see how it goes.

**Comment by snoopdouglas** [comment]
Blasting through the sound section, adding a bit on streaming now. Hopefully it'll be done by the end of today (UTC).

Does anyone have any suggestions on what to implement in the gameplay section? Needs to be very simple - Tetris and Pong are what spring to mind for me. They really have been done to death, but maybe that's not a bad thing, I dunno.

**Edit:** all done. I've renamed AriesNL's new section to 'Advanced game structure' as a continuation of the 'Basic game structure' that starts the tutorial. In the interests of brevity, I still think the gameplay section's code should fit inside one file if possible; juggling several files in a tutorial is more often than not a pain in the arse for readers. I understand it'll be challenging to keep an entire game 'brief', but this is ideally what I'd like.

**Comment by SiegeLord** [comment]
Space invaders, moon lander, a vertical shooter.

**Comment by stickleprojects** [comment]
i havent got to gravity yet, but itd be great to see one that translates onto screen (box2d does NOT seem to translate very well unless im missing something obvious - and also many platformers skip proper physics because they arent "real" enough), space invaders does seem like a good shout tho

**Comment by stickleprojects** [comment]
i realise i might be filling this comment stuff with irrelevent content and questions - please tell me if ther's a better medium or forum and ill move over to there

**Comment by stickleprojects** [comment]
> Ah well, in that case you might want to either:
> 
> * [Emulate an Amiga](https://fs-uae.net/)
> * Fork out a modest amount of cash for [Renoise](https://www.renoise.com/shop)
> * Run [OpenMPT](https://openmpt.org/download) with WINE

went with OpenMPT on Wine and managed to create something to give me a start, and to realise that i dont' enjoy re-crafting music by ear - will look at the latest code and get my background music playing after ive made a few more logic improvements (nice to show some progress) (@snoopdouglas apologies, assumed github would credit you automatically)

**Comment by snoopdouglas** [comment]
> i realise i might be filling this comment stuff with irrelevent content and questions - please tell me if ther's a better medium or forum and ill move over to there

Nah, I reckon this is the perfect place. It's good to have an 'issues' section that sits right next to the wiki. :)

**Comment by stickleprojects** [comment]
space invaders- a single sprite per alien and player (reuse the ALLEGRO_BITMAP stuff, obvs), cos they explode immediately, but multiple sprites for each of the "bases" at the bottom (so each can explode and leave the base intact) plus a few for bullets and one for the random spaceship? im hoping that the bases dont move so less logic and no animation; each wave is a single set of animatinos for aliens so assuming we can swap out the AEELGRO_BITMAP shouldn't take up too much ram
alternatively; a single sprite for the base, and replicate the ALLEGRO_BMP 4 times, on collision, edit the bmp in memory to replace "exploded" bits with transparent colour. collision detection more complicated but less ram to hold the NPCs - thoughts? 
perhaps im over-thinking this stuff

**Comment by stickleprojects** [comment]
On this,  David the8bitguy does a mean shorthand Tetris clone that might be worth investigating not sure how easy it is to understand tho.
Personally ill be pushing a variant of component dev unless you guys really want different and simpler

**Comment by snoopdouglas** [comment]
Space invaders or any kind of shooter is a good shout, I reckon, especially with fixed/simple AI. If we're going down the 'destructible bases' route, this could also be useful to teach the reader about the sluggishness of *reading* textures in the GPU age.

As for component dev, I'm all for it - just somehow in a single file. Perhaps lots of big separator comments? ;)

I'm now wondering, though, whether two source files might be alright - just so long as we code one after the other in the flow of the tutorial. The two files could be:

* `main.c`, which holds the init/loop/shutdown boilerplate, running the hooks implemented by `game.c`.
* `game.c`, for the game's actual logic and draw code.

I feel this might educate on abstraction, and Allegro's "you write the engine" philosophy.

We'll also need assets. SpriteLib for the nostalgia?

**Comment by snoopdouglas** [comment]
@EdwinMartens 

Regarding [this edit](https://github.com/liballeg/allegro_wiki/wiki/Allegro-Vivace:-Basic-game-structure/_compare/586d2601f12fa8b3ca3bb6cc3b0b1bc8802627c7...a79e213f49c027f23de98143c80696a8d84620a8): if you're going to change the code at the start of the tutorial, you need to consider that subsequent discussion of the code - and any further code that was dependent upon it - will also need to be updated to match. The further back that you edit, the more of a chain reaction there'll likely be! So, I'm going to revert this.

It's also worth noting that the reason we `break` the loop at this point, rather than relying on `!done` as a loop condition, is purely to prevent an unnecessary redraw before quitting.

**Comment by connorjclark** [comment]
If you wanted to expand to multiple files, I think folders in the git repo (organizing in folders by steps, perhaps?) is an option. Bonus points if you include cross platform build scripts.

**Comment by Steikel** [comment]
Ok, I just reached this point and really wanted to thank for all the work that has been done. This is a really good tutorial an it gives me the feeling to be able to start with Allegro.
But I have to say, that I was crushed too, when I saw the TODO-mark at the Advanced game structure section. ^^ I was really looking forward to it. But I'm thankfull for all this stuff here anyway!

**Comment by snoopdouglas** [comment]
No contribution has been made to 'advanced game structure', so I'm removing it. Straight into gameplay.

**Comment by snoopdouglas** [comment]
I'm now creating the game. I've gone for a very, very simple space shooter. I'm trying to pack as many simple concepts into as small a space as possible; target is around 750 lines, though less if possible. The reader will be taught in a modular fashion, but we're sticking with a one-file build.

On top of what the reader has already been taught, the techniques we're introducing here are as follows:

* Spritesheet
* Time-incremental difficulty
* A (very) simple actor allocation system
* Score counter
* Dumb-as-hell AI
* Game over screen

**Comment by snoopdouglas** [comment]
All done, though I trimmed down the list of concepts in the final game considerably; the file was just getting too huge.

Please open new issues / edit it yourself if you feel any part of it is unclear - though in the case of the latter **make sure any code changes are proofread** - lots of code gets referenced again later on.
