### ISSUE TITLE
Wrong link on main site

### ISSUE THREAD

**Issue by aleus** [liballeg/allegro_wiki#10]
Wrong link bellow.
![sBBTrikDtq](https://user-images.githubusercontent.com/1224122/85116919-b4cc2300-b226-11ea-85d6-5b3c46e48f77.png)

**Comment by SiegeLord** [comment]
Thanks, it's now fixed.

**Comment by aleus** [comment]
I also found broken links to wiki on page https://liballeg.org/download.html/

**Comment by SiegeLord** [comment]
Thanks, I went through and fixed most of the rest.
