### ISSUE TITLE
Data privacy violation

### ISSUE THREAD

**Issue by hdlopesrocha** [liballeg/allegro_wiki#11]
Hello!

I'm contacting you because you are exposing personal information about me:
https://www.allegro.cc/members/hdlopesrocha

Can you please remove my account or hide my location?
I tried to login but you have no option to recover the password (and I don't even remember what was the e-mail I used to register)

Thanks ;-)
Henrique Rocha

**Comment by SiegeLord** [comment]
We are not in control of what happens on that website. I think I'd recommend making a new account there and then sending a PM to https://www.allegro.cc/members/matthew.leverton/ with your request.

**Comment by leegibsonhoward** [comment]
Not sure if your issue has been resolved or not. 

But, it is possible to reset your password: [Allegro.cc reset password](https://www.allegro.cc/account/forgot)

I just reset my account from 2012 and had to take a few guesses at which email I used.

Maybe you could try a few of your old emails.
