### ISSUE TITLE
Example code compiles, but shows errors unless <stdbool.h> is included. 

### ISSUE THREAD

**Issue by ai8194** [liballeg/allegro_wiki#13]
On Windows with VS Code. "bool redraw = true" generates two errors:

1. function "redraw" may not be initialized.

2. identifier "true" is undefined.

Later assignments to the variable also generate "expression must be a modifiable lvalue".

It still compiles despite this, but this makes me hesitant to actually use allegro at this point.  

In a similar vein, the install instructions should be updated, as mingw64 has a subdirectory with its own bin, include, and lib where allegro needs to be installed, rather than just the top level versions of those folders.

**Comment by ai8194** [comment]
This is as mentioned (seemingly) fixed by including <stdbool.h>

**Comment by SiegeLord** [comment]
Thanks, I've made those changes.
