### ISSUE TITLE
Should mention console behavior in earlier parts (such as quickstart).

### ISSUE THREAD

**Issue by ai8194** [liballeg/allegro_wiki#14]
In the quickstart guide, you only mention the hello world program opening a single window, while on windows it will actually open the window and a console behind it. You utilize this console in the Basic Game Structure section, which might be a little confusing if someone tried to fix the console appearing during the quickstart guide by using the -mwindows compile flag. I recommend mentioning the console behavior in the guide, as it seemed like an error on my part when I read it.

**Comment by snoopdouglas** [comment]
[I've added this here.](https://github.com/liballeg/allegro_wiki/wiki/Quickstart#windows-mingw)
