### ISSUE TITLE
Problem in linking for Hello World of Vivace guide

### ISSUE THREAD

**Issue by enrico-campagna** [liballeg/allegro_wiki#15]
Sorry to bother you with such a basic question.
I installed last version of Code Block with minGW 8.1.0, I downloaded the precompiled version of Allegro 5.2.6 with the dynamic libraries, I followed the instruction of "Install Allegro from binaries for MinGW and CodeBlocks" and I tied to build the exe of "Hello World" of "Vivace" guide.
This is the beginning of the build log:

i686-w64-mingw32-c++.exe -Wall -O2 -IC:\allegro\include -IC:\allegro_deps\include -IC:\allegro\include -IC:\allegro\bin -IC:\allegro\include\allegro5 -c "C:\Users\Enrico\Documents\C++\Programs\.objs\Hello World2\Main.cpp" -o obj\Release\Main.o
i686-w64-mingw32-g++.exe -LC:\allegro\lib -LC:\allegro\bin -LC:\allegro -LC:\allegro\lib -LC:\allegro_deps\lib -LC:\allegro\bin -o "bin\Release\Hello World2.exe" obj\Release\Main.o  -lgcc_eh -lallegro_monolith.dll -s -static-libstdc++ -static-libgcc  
obj\Release\Main.o:Main.cpp:(.text.startup+0x24): undefined reference to `al_install_system'
obj\Release\Main.o:Main.cpp:(.text.startup+0x29): undefined reference to `al_install_keyboard'
obj\Release\Main.o:Main.cpp:(.text.startup+0x3d): undefined reference to `al_create_timer'
obj\Release\Main.o:Main.cpp:(.text.startup+0x48): undefined reference to `al_create_event_queue'
obj\Release\Main.o:Main.cpp:(.text.startup+0x5e): undefined reference to `al_create_display'

There is something wrong with the linker... What can I do?
Thank you in advance,

Enrico

**Comment by EdgarReynaldo** [comment]
Your settings are repetitive and not quite right for the linker.

You should link to the monolith if available, or allegro and the addons if that is your build type.

It looks like you're linking to the monolith dll and the static C libraries, that's fine. One thing is you're passing too many directories to -L . You only need -LC:\allegro\lib .

**Comment by EdgarReynaldo** [comment]
Also, the undefined references are probably coming from the mismatch in compiler versions between the version bundled with CodeBlocks and the version used to build Allegro.

**Comment by EdgarReynaldo** [comment]
I added a warning note to the page for CodeBlocks, MinGW and Allegro 5. It states, "Your MinGW version must match the version used to build allegro exactly".

**Comment by enrico-campagna** [comment]
Thank you a lot!

Il giorno sab 20 nov 2021 alle ore 18:38 Zorro ***@***.***>
ha scritto:
