### ISSUE TITLE
I'm unable to create a new account on allegro.cc

### ISSUE THREAD

**Issue by sukhchain9935** [liballeg/allegro_wiki#17]
I'm unable to create a new account on allegro.cc, or login with my existing account on a different system than my Personal Laptop on which I created my account.

I was able to create an account, I even changed the password, but I was not able to login to my account or again change the password, as there's no option for doing so. The Login with Google feature isn't working either.

**Comment by SiegeLord** [comment]
I made a thread for you, good luck! https://www.allegro.cc/forums/thread/618366
