### ISSUE TITLE
Homebrew does not install Allegro to the correct location on Apple Silicon

### ISSUE THREAD

**Issue by Wolfos** [liballeg/allegro_wiki#18]
"Allegro should be installed into /usr/local/lib and /usr/local/include."
After installation there is nothing Allegro related in either of those two directories, and the example fails to compile.

It is instead installed under /opt/homebrew/Cellar/allegro/

**Comment by Wolfos** [comment]
This appears to be Homebrew's default location for ARM64 systems.

**Comment by snoopdouglas** [comment]
@Wolfos this is probably one for the [main Allegro repo](https://github.com/liballeg/allegro5).
