### ISSUE TITLE
Allegro quickstart tutorial 'Hello World' doesn't react to display close event

### ISSUE THREAD

**Issue by julia-bell** [liballeg/allegro_wiki#2]
When I ran the Hello World example I found that the program didn't respond to me clicking the X button at the corner of the window. In order to fix this I had to add the following line:

`al_register_event_source(queue, al_get_display_event_source(disp));`

For reference, I'm using Allegro 5 on Debian Linux (aarch64).

**Comment by snoopdouglas** [comment]
Good spot, will add this now.

**Comment by snoopdouglas** [comment]
Done - wiki commits:

73f396e582da53ca8491d37686d16785bad54217
586d2601f12fa8b3ca3bb6cc3b0b1bc8802627c7
