### ISSUE TITLE
Can't clone wiki locally

### ISSUE THREAD

**Issue by JoseLuis-AL** [liballeg/allegro_wiki#20]
Hello.

When I try to clone the wiki locally I get this in the console (powershell and cmd in windows 10):

```powershell
PS C:\Users\JoseLuis_AL\desktop> git clone https://github.com/liballeg/allegro_wiki.wiki.git                            
Cloning into 'allegro_wiki.wiki'...                                                                                     
remote: Enumerating objects: 2106, done.                                                                                
Receiving objects:  95% (2001/2106), 12.18 MiBremote: Total 2106 (delta 0), reused 0 (delta 0), pack-reused 2106 | 5.50 
Receiving objects:                                                                                                      
Receiving objects: 100% (2106/2106), 12.57 MiB | 5.51 MiB/s, done.                                                      
Resolving deltas: 100% (1306/1306), done.                                                                               
error: invalid path 'Allegro-Vivace:-Basic-game-structure.md'                                                           
fatal: unable to checkout working tree                                                                                  
warning: Clone succeeded, but checkout failed.                                                                          
You can inspect what was checked out with 'git status'                                                                  
and retry with 'git restore --source=HEAD :/'                                                                           
```

**Note**: This is my first time trying to clone the wiki from a repository.

**Comment by SiegeLord** [comment]
That's... an interesting problem. The issue, as the errors says, is that some of the articles have invalid characters in their filenames as far as Windows is concerned (in this case, the `:` character). The internet has a few workarounds, but maybe we could rename the articles or something like that?

**Comment by JoseLuis-AL** [comment]
Renaming files to remove these characters can be a good solution, especially for everyone trying to clone the repository on windows.

**Comment by EdgarReynaldo** [comment]
The URL name is incorrect. You use 'https://github.com/liballeg/allegro_wiki.wiki.git' but it is supposed to be 'https://github.com/liballeg/allegro_wiki.git' .

**Comment by f4biopedro** [comment]
> The URL name is incorrect. You use 'https://github.com/liballeg/allegro_wiki.wiki.git' but it is supposed to be 'https://github.com/liballeg/allegro_wiki.git' .

at the wiki there is a pane that says "Clone this wiki locally" with the URL [https://github.com/liballeg/allegro_wiki.wiki.git](url)
