### ISSUE TITLE
Graphics- invalid use of 'this' out of non-static member function

### ISSUE THREAD

**Issue by UgurcanAkkok** [liballeg/allegro_wiki#3]
Since `this` is a keyword and it should be used in non-static member function, when i compile the program it throws me lots of error, i can fix that with changing `this` to anything that is not a keyword in c++, but i think wiki should warn or change somethings.

**Comment by snoopdouglas** [comment]
We're using C rather than C++ in Vivace, where `this` isn't a keyword. Might not be a bad idea to change it in order to prevent that ambiguity, though.

**Comment by snoopdouglas** [comment]
[Loop pointer variable changed from `this` to `b`.](https://github.com/liballeg/allegro_wiki/wiki/Allegro-Vivace:-Graphics/_compare/586d2601f12fa8b3ca3bb6cc3b0b1bc8802627c7...caa142a974703752eacaa865f682d2e71ea84127)
