### ISSUE TITLE
wiki is down

### ISSUE THREAD

**Issue by connorjclark** [liballeg/allegro_wiki#4]
http://wiki.allegro.cc/ doesnt load

**Comment by connorjclark** [comment]
Oh, I see this repo has a GH wiki.

Still, the above link from the main liballeg site is dead.

**Comment by snoopdouglas** [comment]
Seems to be back up now, and yeah we're only keeping it alive for now whilst content is transitioned. This wiki is by no means complete, but the info in the old wiki is so out-of-date that I think it's best to look here first, then search the Allegro.cc forums if you're having trouble.
