### ISSUE TITLE
Broken links for 'Learning C and C++' page

### ISSUE THREAD

**Issue by snoopdouglas** [liballeg/allegro_wiki#5]
@EdwinMartens edited this article earlier, changing its title. This broke the links on the home and tutorials pages; please be careful when renaming things.

For the moment, I've restored it to its original title. Please [note the footer](https://github.com/liballeg/allegro_wiki/wiki/Learning-C#wiki-footer) of the article, which explains why the page is currently just called 'Learning C'.

**Comment by EdwinMartens** [comment]
Oops.. sorry 😉

**Comment by snoopdouglas** [comment]
If you've got any ideas about how to circumvent the wiki's stupid page name rules, please go ahead :p
