### ISSUE TITLE
Homebrew install failure

### ISSUE THREAD

**Issue by whittenjaw85** [liballeg/allegro_wiki#9]
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "opusfile--music_48kbps.opus"
Download failed: https://www.opus-codec.org/examples/samples/music_48kbps.opus

**Comment by SiegeLord** [comment]
Can you clarify what commands you did to get that error, and where you found those commands?

**Comment by snoopdouglas** [comment]
I think this is something to do with the tutorial. No idea what it has to do with brew.

**Edit** - just checked, [this link](https://github.com/liballeg/allegro_wiki/wiki/audio/music_128kbps.opus) is the one on Vivace and it works fine.

@whittenjaw85 can you enlighten us? Feel free to re-open if so.
